// frontend-react/src/App.jsx
import { BrowserRouter, Link, Navigate, Route, Routes } from 'react-router-dom'
import ProductListPage from './pages/ProductListPage'
import ProductDetailPage from './pages/ProductDetailPage'
import ProductFormPage from './pages/ProductFormPage'
import './App.css'

function App() {
  return (
    <BrowserRouter>
      <nav className="navbar navbar-expand-lg navbar-dark topbar">
        <div className="container">
          <Link className="navbar-brand" to="/productos">
            SportStock · React
          </Link>
          <Link className="btn btn-sm btn-light fw-semibold" to="/productos/nuevo">
            Nuevo producto
          </Link>
        </div>
      </nav>

      <main className="container page-wrap">
        <Routes>
          <Route path="/" element={<Navigate to="/productos" replace />} />
          <Route path="/productos" element={<ProductListPage />} />
          <Route path="/productos/nuevo" element={<ProductFormPage />} />
          <Route path="/productos/editar/:id" element={<ProductFormPage />} />
          <Route path="/productos/:id" element={<ProductDetailPage />} />
          <Route path="*" element={<Navigate to="/productos" replace />} />
        </Routes>
      </main>
    </BrowserRouter>
  )
}

export default App

// frontend-angular/src/app/app.ts
import { Component } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, RouterLink],
  template: `
    <nav class="navbar navbar-expand-lg navbar-dark topbar">
      <div class="container">
        <a class="navbar-brand" routerLink="/productos">SportStock · Angular</a>
        <a class="btn btn-sm btn-light fw-semibold" routerLink="/productos/nuevo">Nuevo producto</a>
      </div>
    </nav>

    <main class="container page-wrap">
      <router-outlet></router-outlet>
    </main>
  `,
  styleUrl: './app.css'
})
export class App {}
